export type FeatureDecision = "build" | "simple" | "optional" | "later";

export interface FeatureScopeItem {
  id: string;
  module: string;
  feature: string;
  description: string;
  approval: string;
  decision: FeatureDecision;
  priority: string;
  targetVersion: string;
  note: string;
}

export const featureScope: FeatureScopeItem[] = [
  {
    "id": "F001",
    "module": "首页工作台",
    "feature": "首页工作台",
    "description": "待办、经营卡片、快捷入口、预警",
    "approval": "简单版",
    "decision": "simple",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做常用入口和待办壳层，经营分析后置"
  },
  {
    "id": "F002",
    "module": "首页工作台",
    "feature": "左侧模块导航",
    "description": "销售、采购、库存、生产等菜单",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "ERP 主入口"
  },
  {
    "id": "F003",
    "module": "首页工作台",
    "feature": "多页签工作区",
    "description": "像金蝶一样打开多个业务页",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "提升多单据切换效率"
  },
  {
    "id": "F004",
    "module": "首页工作台",
    "feature": "全局搜索",
    "description": "搜单据、客户、商品、功能入口",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "可先做功能入口搜索"
  },
  {
    "id": "F005",
    "module": "首页工作台",
    "feature": "消息/待办中心",
    "description": "审批、预警、系统消息",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "跟工作流一起完善"
  },
  {
    "id": "F006",
    "module": "首页工作台",
    "feature": "操作日志",
    "description": "记录用户、时间、动作、对象",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "审计和追责基础"
  },
  {
    "id": "F007",
    "module": "首页工作台",
    "feature": "附件中心",
    "description": "单据上传图片、PDF、合同",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "看现场是否常用"
  },
  {
    "id": "F008",
    "module": "首页工作台",
    "feature": "导入/导出",
    "description": "Excel 导入、导出列表",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "基础资料和列表必须具备"
  },
  {
    "id": "F009",
    "module": "首页工作台",
    "feature": "打印/套打",
    "description": "单据打印模板",
    "approval": "简单版",
    "decision": "simple",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做固定模板，设计器后置"
  },
  {
    "id": "F010",
    "module": "基础资料",
    "feature": "商品资料",
    "description": "物料、成品、半成品、单位、规格",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "所有链路基础"
  },
  {
    "id": "F011",
    "module": "基础资料",
    "feature": "BOM",
    "description": "成品和子件关系、版本、审核",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "生产与缺料分析核心"
  },
  {
    "id": "F012",
    "module": "基础资料",
    "feature": "客户资料",
    "description": "客户、联系人、结算信息",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "销售基础"
  },
  {
    "id": "F013",
    "module": "基础资料",
    "feature": "供应商资料",
    "description": "供应商、联系人、采购结算",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "采购基础"
  },
  {
    "id": "F014",
    "module": "基础资料",
    "feature": "仓库资料",
    "description": "仓库、仓位、是否允许负库存",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "库存基础"
  },
  {
    "id": "F015",
    "module": "基础资料",
    "feature": "部门/车间",
    "description": "生产车间、业务部门",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "生产任务必需"
  },
  {
    "id": "F016",
    "module": "基础资料",
    "feature": "员工/用户",
    "description": "登录账号、员工、角色",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "权限基础"
  },
  {
    "id": "F017",
    "module": "基础资料",
    "feature": "账户资料",
    "description": "现金、银行、存款账户",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "收付款基础"
  },
  {
    "id": "F018",
    "module": "基础资料",
    "feature": "计量单位",
    "description": "PCS、套、件等",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "商品基础"
  },
  {
    "id": "F020",
    "module": "基础资料",
    "feature": "价格资料",
    "description": "客户价格、采购价格、价格等级",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "报价/价格管控时再做"
  },
  {
    "id": "F021",
    "module": "销售管理",
    "feature": "销售报价单",
    "description": "给客户报价",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "若销售直接下订单可不做"
  },
  {
    "id": "F022",
    "module": "销售管理",
    "feature": "销售订单",
    "description": "接单、跟踪执行",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "销售主链路"
  },
  {
    "id": "F023",
    "module": "销售管理",
    "feature": "销售出库单",
    "description": "发货扣库存",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "库存影响关键"
  },
  {
    "id": "F024",
    "module": "销售管理",
    "feature": "销售退货单",
    "description": "客户退货入库",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "逆向链路"
  },
  {
    "id": "F026",
    "module": "销售管理",
    "feature": "销售收款",
    "description": "出库后收款",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "应收闭环"
  },
  {
    "id": "F027",
    "module": "销售管理",
    "feature": "销售退款",
    "description": "退货后退款",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "逆向资金"
  },
  {
    "id": "F028",
    "module": "销售管理",
    "feature": "销售税票",
    "description": "开票登记",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "财务票据增强"
  },
  {
    "id": "F029",
    "module": "销售管理",
    "feature": "销售报表",
    "description": "销售明细、汇总、排行、利润",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做明细/汇总/订单跟踪"
  },
  {
    "id": "F033",
    "module": "采购管理",
    "feature": "采购订单",
    "description": "向供应商下单",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "采购主链路"
  },
  {
    "id": "F034",
    "module": "采购管理",
    "feature": "采购入库单",
    "description": "到货入库",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "库存影响关键"
  },
  {
    "id": "F035",
    "module": "采购管理",
    "feature": "采购退货单",
    "description": "退货给供应商",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "逆向链路"
  },
  {
    "id": "F036",
    "module": "采购管理",
    "feature": "采购付款",
    "description": "入库后付款",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "应付闭环"
  },
  {
    "id": "F037",
    "module": "采购管理",
    "feature": "采购退款",
    "description": "退货后退款",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "逆向资金"
  },
  {
    "id": "F038",
    "module": "采购管理",
    "feature": "采购税票",
    "description": "进项票登记",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "财务票据增强"
  },
  {
    "id": "F039",
    "module": "采购管理",
    "feature": "智能补货/以销定购",
    "description": "自动建议采购",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "与 MRP/缺料分析合并考虑"
  },
  {
    "id": "F040",
    "module": "采购管理",
    "feature": "采购报表",
    "description": "采购明细、汇总、跟踪",
    "approval": "简单版",
    "decision": "simple",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做明细/汇总"
  },
  {
    "id": "F041",
    "module": "库存管理",
    "feature": "库存查询",
    "description": "即时库存、可用库存",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "日常高频"
  },
  {
    "id": "F042",
    "module": "库存管理",
    "feature": "商品收发明细",
    "description": "每笔入出库流水",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "库存可追溯"
  },
  {
    "id": "F043",
    "module": "库存管理",
    "feature": "其他入库",
    "description": "非采购/生产入库",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "调整库存必需"
  },
  {
    "id": "F044",
    "module": "库存管理",
    "feature": "其他出库",
    "description": "非销售/生产出库",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "调整库存必需"
  },
  {
    "id": "F045",
    "module": "库存管理",
    "feature": "调拨单",
    "description": "仓库之间调货",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "多仓库时要"
  },
  {
    "id": "F046",
    "module": "库存管理",
    "feature": "移仓单",
    "description": "同仓不同仓位移动",
    "approval": "可选",
    "decision": "optional",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "启用仓位后再做"
  },
  {
    "id": "F047",
    "module": "库存管理",
    "feature": "盘点任务/盘点单",
    "description": "库存盘点、盘盈盘亏",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "库存修正必需"
  },
  {
    "id": "F048",
    "module": "库存管理",
    "feature": "盘盈单/盘亏单",
    "description": "盘点差异调整",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "盘点配套"
  },
  {
    "id": "F049",
    "module": "库存管理",
    "feature": "预留单",
    "description": "锁定库存给订单",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "库存紧张时有价值"
  },
  {
    "id": "F052",
    "module": "库存管理",
    "feature": "库存预警",
    "description": "低库存提醒",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "采购提醒基础"
  },
  {
    "id": "F055",
    "module": "库存管理",
    "feature": "业务关账/期末结账",
    "description": "锁定期间、防止改历史单",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "第一版先谨慎"
  },
  {
    "id": "F056",
    "module": "生产管理",
    "feature": "生产任务单",
    "description": "下达生产任务",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "生产主链路"
  },
  {
    "id": "F057",
    "module": "生产管理",
    "feature": "生产领料单",
    "description": "从仓库领材料",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "材料出库"
  },
  {
    "id": "F058",
    "module": "生产管理",
    "feature": "生产退料单",
    "description": "多领材料退回",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "逆向链路"
  },
  {
    "id": "F059",
    "module": "生产管理",
    "feature": "产品入库单",
    "description": "成品完工入库",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "成品入库"
  },
  {
    "id": "F060",
    "module": "生产管理",
    "feature": "产品退库单",
    "description": "成品退回生产",
    "approval": "可选",
    "decision": "optional",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "低频逆向"
  },
  {
    "id": "F061",
    "module": "生产管理",
    "feature": "材料报废单",
    "description": "生产中材料报废",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "车间损耗记录"
  },
  {
    "id": "F062",
    "module": "生产管理",
    "feature": "BOM 正向/反查",
    "description": "查成品用料、子件被哪些成品用",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "BOM 管理高频"
  },
  {
    "id": "F063",
    "module": "生产管理",
    "feature": "BOM 成本查询",
    "description": "按 BOM 估算成本",
    "approval": "要（实施后置）",
    "decision": "later",
    "priority": "P1",
    "targetVersion": "第二版",
    "note": "用户审批为要；但第一版不做出库成本核算、生产成本核算，库存流水金额字段留空，无可信成本口径，先不做可计算版本。"
  },
  {
    "id": "F064",
    "module": "生产管理",
    "feature": "BOM 批量修改",
    "description": "批量替换子件",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "产品多时再做"
  },
  {
    "id": "F065",
    "module": "生产管理",
    "feature": "物料需求建议/MRP",
    "description": "按订单/BOM 算缺料",
    "approval": "后面重点做",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "可先做简单缺料建议"
  },
  {
    "id": "F066",
    "module": "生产管理",
    "feature": "齐套分析",
    "description": "判断材料是否够生产",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "工厂实用性强"
  },
  {
    "id": "F067",
    "module": "生产管理",
    "feature": "足缺料分析",
    "description": "查缺什么料",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "采购和排产关键"
  },
  {
    "id": "F068",
    "module": "生产管理",
    "feature": "计划订单",
    "description": "生产计划中间单",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "复杂计划时再做"
  },
  {
    "id": "F069",
    "module": "生产管理",
    "feature": "生产成本核算",
    "description": "人工、制造费用、材料成本分配",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "第一版不强算"
  },
  {
    "id": "F070",
    "module": "生产管理",
    "feature": "班组/生产汇报",
    "description": "报工、班组产量",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "当前金蝶入口不可见"
  },
  {
    "id": "F071",
    "module": "委外管理",
    "feature": "委外加工单",
    "description": "发给外协加工",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "有外协才做"
  },
  {
    "id": "F072",
    "module": "委外管理",
    "feature": "委外发料",
    "description": "发材料给外协",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "有外协才做"
  },
  {
    "id": "F073",
    "module": "委外管理",
    "feature": "委外退料",
    "description": "外协退料",
    "approval": "可选",
    "decision": "optional",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "低频逆向"
  },
  {
    "id": "F074",
    "module": "委外管理",
    "feature": "委外入库",
    "description": "外协成品入库",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "有外协才做"
  },
  {
    "id": "F075",
    "module": "委外管理",
    "feature": "委外退货",
    "description": "外协退货",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "低频逆向"
  },
  {
    "id": "F076",
    "module": "委外管理",
    "feature": "委外 BOM",
    "description": "外协用 BOM",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "按外协复杂度决定"
  },
  {
    "id": "F077",
    "module": "委外管理",
    "feature": "委外费用",
    "description": "加工费",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "有外协结算才做"
  },
  {
    "id": "F078",
    "module": "委外管理",
    "feature": "委外成本核算",
    "description": "外协成本计算",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P3",
    "targetVersion": "后续",
    "note": "复杂成本后置"
  },
  {
    "id": "F079",
    "module": "委外管理",
    "feature": "委外报表",
    "description": "委外明细、执行、材料",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "有外协才做"
  },
  {
    "id": "F080",
    "module": "应收应付/资金",
    "feature": "收款单",
    "description": "客户收款",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "销售资金闭环"
  },
  {
    "id": "F081",
    "module": "应收应付/资金",
    "feature": "收款退款单",
    "description": "客户退款",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "销售逆向资金"
  },
  {
    "id": "F082",
    "module": "应收应付/资金",
    "feature": "付款单",
    "description": "供应商付款",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "采购资金闭环"
  },
  {
    "id": "F083",
    "module": "应收应付/资金",
    "feature": "付款退款单",
    "description": "供应商退款",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "采购逆向资金"
  },
  {
    "id": "F084",
    "module": "应收应付/资金",
    "feature": "预收款",
    "description": "客户提前付款",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "按现场结算习惯决定"
  },
  {
    "id": "F085",
    "module": "应收应付/资金",
    "feature": "预付款",
    "description": "给供应商预付",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "按现场结算习惯决定"
  },
  {
    "id": "F086",
    "module": "应收应付/资金",
    "feature": "其他收入/支出",
    "description": "杂项收支",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "简单财务记录"
  },
  {
    "id": "F087",
    "module": "应收应付/资金",
    "feature": "资金转账",
    "description": "银行/现金账户互转",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "账户管理基础"
  },
  {
    "id": "F088",
    "module": "应收应付/资金",
    "feature": "手动核销",
    "description": "应收应付和收付款匹配",
    "approval": "简单版",
    "decision": "simple",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做按单核销"
  },
  {
    "id": "F089",
    "module": "应收应付/资金",
    "feature": "自动核销",
    "description": "自动匹配收付款",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "算法和规则后置"
  },
  {
    "id": "F090",
    "module": "应收应付/资金",
    "feature": "客户/供应商对账",
    "description": "对账单",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "日常财务对账"
  },
  {
    "id": "F091",
    "module": "应收应付/资金",
    "feature": "应收应付报表",
    "description": "汇总、明细、预警",
    "approval": "简单版",
    "decision": "simple",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做汇总和明细"
  },
  {
    "id": "F093",
    "module": "系统设置",
    "feature": "编码规则",
    "description": "单据自动编号",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "各单据编号基础"
  },
  {
    "id": "F094",
    "module": "系统设置",
    "feature": "用户管理",
    "description": "用户、角色、权限",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "系统基础"
  },
  {
    "id": "F095",
    "module": "系统设置",
    "feature": "功能权限",
    "description": "谁能看/新增/审核/删除",
    "approval": "要",
    "decision": "build",
    "priority": "P0",
    "targetVersion": "第一版",
    "note": "权限基础"
  },
  {
    "id": "F096",
    "module": "系统设置",
    "feature": "字段权限",
    "description": "谁能看/改某些字段",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "管理细化时做"
  },
  {
    "id": "F097",
    "module": "系统设置",
    "feature": "数据权限",
    "description": "只能看自己/部门/客户数据",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "按组织管理需求决定"
  },
  {
    "id": "F098",
    "module": "系统设置",
    "feature": "单据操作控制",
    "description": "审核后能不能改、本人限制",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "防误改历史单据"
  },
  {
    "id": "F099",
    "module": "系统设置",
    "feature": "审批流/工作流",
    "description": "提交、审批、任务中心",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "先做单级或固定流程"
  },
  {
    "id": "F101",
    "module": "系统设置",
    "feature": "系统参数",
    "description": "负库存、超量领料等开关",
    "approval": "要",
    "decision": "build",
    "priority": "P1",
    "targetVersion": "第一版",
    "note": "影响业务规则"
  },
  {
    "id": "F102",
    "module": "系统设置",
    "feature": "消息预警设置",
    "description": "库存、信用、交期提醒",
    "approval": "要",
    "decision": "build",
    "priority": "P2",
    "targetVersion": "第二版",
    "note": "先做库存预警"
  },
  {
    "id": "F103",
    "module": "系统设置",
    "feature": "打印模板设计器",
    "description": "可视化设计打印模板",
    "approval": "后面再说",
    "decision": "later",
    "priority": "P3",
    "targetVersion": "后续",
    "note": "固定模板先够用"
  },
  {
    "id": "F104",
    "module": "系统设置",
    "feature": "网络控制/多端互联",
    "description": "金蝶特色能力",
    "approval": "要",
    "decision": "build",
    "priority": "P3",
    "targetVersion": "后续",
    "note": "不建议进入复刻范围"
  }
] as FeatureScopeItem[];
