ALTER TABLE sales_order
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE purchase_order
    ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE sales_out
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE purchase_in
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE production_material_issue
    ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE production_completion
    ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE other_stock_in
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE other_stock_out
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE stock_transfer
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE stock_count
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE stock_count_gain
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE stock_count_loss
    ADD COLUMN IF NOT EXISTS close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS close_reason TEXT,
    ADD COLUMN IF NOT EXISTS closed_by UUID,
    ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS frozen_reason TEXT,
    ADD COLUMN IF NOT EXISTS frozen_by UUID,
    ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS void_reason TEXT,
    ADD COLUMN IF NOT EXISTS void_verified_username VARCHAR(80),
    ADD COLUMN IF NOT EXISTS void_verified_at TIMESTAMPTZ;

ALTER TABLE sales_order_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE purchase_order_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE sales_out_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE purchase_in_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE production_material_issue_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE production_completion_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE other_stock_in_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE other_stock_out_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE stock_transfer_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE stock_count_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE stock_count_gain_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;
ALTER TABLE stock_count_loss_line ADD COLUMN IF NOT EXISTS line_close_status VARCHAR(40) NOT NULL DEFAULT 'OPEN', ADD COLUMN IF NOT EXISTS line_close_reason TEXT, ADD COLUMN IF NOT EXISTS line_frozen_status VARCHAR(40) NOT NULL DEFAULT 'NORMAL', ADD COLUMN IF NOT EXISTS line_frozen_reason TEXT;

CREATE INDEX IF NOT EXISTS idx_sales_order_lifecycle ON sales_order (status, close_status, frozen_status);
CREATE INDEX IF NOT EXISTS idx_purchase_order_lifecycle ON purchase_order (status, close_status, frozen_status);
CREATE INDEX IF NOT EXISTS idx_sales_order_line_lifecycle ON sales_order_line (order_id, line_close_status, line_frozen_status);
CREATE INDEX IF NOT EXISTS idx_purchase_order_line_lifecycle ON purchase_order_line (order_id, line_close_status, line_frozen_status);
