ALTER TABLE md_product
    ADD COLUMN IF NOT EXISTS short_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS barcode VARCHAR(120),
    ADD COLUMN IF NOT EXISTS brand VARCHAR(120),
    ADD COLUMN IF NOT EXISTS product_type VARCHAR(80) NOT NULL DEFAULT '成品',
    ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(8, 4) NOT NULL DEFAULT 13,
    ADD COLUMN IF NOT EXISTS cost_price NUMERIC(18, 6),
    ADD COLUMN IF NOT EXISTS min_sale_price NUMERIC(18, 6),
    ADD COLUMN IF NOT EXISTS remark TEXT;

ALTER TABLE md_customer
    ADD COLUMN IF NOT EXISTS short_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS customer_level VARCHAR(80) NOT NULL DEFAULT '普通客户',
    ADD COLUMN IF NOT EXISTS tax_no VARCHAR(120),
    ADD COLUMN IF NOT EXISTS address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(18, 2),
    ADD COLUMN IF NOT EXISTS settlement_method VARCHAR(80) NOT NULL DEFAULT '月结',
    ADD COLUMN IF NOT EXISTS owner_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS remark TEXT;

ALTER TABLE md_supplier
    ADD COLUMN IF NOT EXISTS short_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS supplier_level VARCHAR(80) NOT NULL DEFAULT '普通供应商',
    ADD COLUMN IF NOT EXISTS tax_no VARCHAR(120),
    ADD COLUMN IF NOT EXISTS address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS bank_account VARCHAR(200),
    ADD COLUMN IF NOT EXISTS settlement_method VARCHAR(80) NOT NULL DEFAULT '月结',
    ADD COLUMN IF NOT EXISTS owner_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS remark TEXT;

ALTER TABLE md_warehouse
    ADD COLUMN IF NOT EXISTS warehouse_type VARCHAR(80) NOT NULL DEFAULT '普通仓',
    ADD COLUMN IF NOT EXISTS manager VARCHAR(120),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(80),
    ADD COLUMN IF NOT EXISTS address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS remark TEXT;
