ALTER TABLE md_product
    ADD COLUMN IF NOT EXISTS is_purchase BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS is_sale BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS is_inventory BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS is_produce BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS is_subcontract BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS default_warehouse_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS sale_unit VARCHAR(80),
    ADD COLUMN IF NOT EXISTS purchase_unit VARCHAR(80),
    ADD COLUMN IF NOT EXISTS bom_unit VARCHAR(80),
    ADD COLUMN IF NOT EXISTS default_supplier_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS issue_warehouse_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS issue_method VARCHAR(80) NOT NULL DEFAULT '按单领料';
