package com.jdy.erp.purchase.application;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.jdy.erp.shared.application.LookupService;
import com.jdy.erp.shared.application.NumberingService;
import com.jdy.erp.shared.application.ValidationService;
import com.jdy.erp.shared.domain.BillStatus;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class PurchaseRequisitionAppService {
    private static final SupplierSnapshot NO_SUPPLIER = new SupplierSnapshot(null, null, null);

    private final JdbcTemplate jdbcTemplate;
    private final LookupService lookupService;
    private final ValidationService validationService;
    private final NumberingService numberingService;

    public PurchaseRequisitionAppService(
        JdbcTemplate jdbcTemplate,
        LookupService lookupService,
        ValidationService validationService,
        NumberingService numberingService
    ) {
        this.jdbcTemplate = jdbcTemplate;
        this.lookupService = lookupService;
        this.validationService = validationService;
        this.numberingService = numberingService;
    }

    /**
     * Creates the single editable requisition generated by one production-plan
     * push-down.  The caller owns the surrounding production transaction; this
     * method joins that transaction and deliberately does not use an isolated
     * transaction or auto-audit the document.
     */
    @Transactional
    public Map<String, Object> createFromProductionPlan(
        String planId,
        String planNo,
        List<GeneratedLine> generatedLines
    ) {
        if (generatedLines == null || generatedLines.isEmpty()) {
            return Map.of();
        }

        var normalizedPlanId = requiredUuid(planId, "生产计划主键");
        var normalizedPlanNo = validationService.required(planNo, "生产计划单号");
        var planRows = jdbcTemplate.queryForList("""
            SELECT id::text AS id
            FROM production_plan
            WHERE id = ?::uuid
              AND bill_no = ?
            FOR UPDATE
            """, normalizedPlanId, normalizedPlanNo);
        if (planRows.isEmpty()) {
            throw badRequest("生产计划来源不存在或与单号不匹配");
        }

        var existing = jdbcTemplate.queryForObject("""
            SELECT COUNT(*)
            FROM purchase_requisition
            WHERE source_plan_id = ?::uuid
            """, Integer.class, normalizedPlanId);
        if (existing != null && existing > 0) {
            throw conflict("生产计划已生成采购申请，不能重复下推");
        }

        var resolvedLines = new ArrayList<ResolvedGeneratedLine>();
        var sequence = 1;
        for (var generatedLine : generatedLines) {
            resolvedLines.add(resolveGeneratedLine(normalizedPlanId, sequence, generatedLine));
            sequence += 1;
        }

        var commonSupplier = commonSupplier(resolvedLines.stream()
            .map(ResolvedGeneratedLine::supplier)
            .toList());
        var department = commonDepartment(resolvedLines);
        var billNo = numberingService.nextBillNo("purchaseRequisition");
        var header = jdbcTemplate.queryForMap("""
            INSERT INTO purchase_requisition (
                bill_no, source_plan_id, source_plan_no, supplier_id,
                supplier_code_snapshot, supplier_name_snapshot, bill_date,
                department, status, total_amount, owner_name
            )
            VALUES (?, ?::uuid, ?, ?::uuid, ?, ?, CURRENT_DATE, ?, ?, 0, ?)
            RETURNING id::text AS id, bill_no AS "billNo", status
            """,
            billNo,
            normalizedPlanId,
            normalizedPlanNo,
            commonSupplier.id(),
            commonSupplier.code(),
            commonSupplier.name(),
            department,
            BillStatus.DRAFT.name(),
            "系统生成"
        );

        var requisitionId = String.valueOf(header.get("id"));
        for (var line : resolvedLines) {
            jdbcTemplate.update("""
                INSERT INTO purchase_requisition_line (
                    requisition_id, line_no, source_plan_id, source_plan_line_id,
                    source_plan_no, source_bom_line_id, source_task_id,
                    source_level, source_bom_code_snapshot,
                    source_bom_version_no, source_bom_line_no, source_bom_path,
                    product_id, product_code_snapshot, product_name_snapshot,
                    product_spec_snapshot, product_unit_snapshot,
                    net_weight_snapshot, gross_weight_snapshot, warehouse_id,
                    supplier_id, supplier_code_snapshot, supplier_name_snapshot,
                    qty, ordered_qty, planned_qty, plan_delivery_date
                )
                VALUES (
                    ?::uuid, ?, ?::uuid, ?::uuid, ?, ?::uuid, ?::uuid,
                    ?, ?, ?, ?, ?, ?::uuid, ?, ?, ?, ?, ?, ?, ?::uuid,
                    ?::uuid, ?, ?, ?, 0, 0, ?
                )
                """,
                requisitionId,
                line.lineNo(),
                normalizedPlanId,
                line.sourcePlanLineId(),
                normalizedPlanNo,
                line.sourceBomLineId(),
                line.sourceTaskId(),
                line.sourceLevel(),
                line.sourceBomCode(),
                line.sourceBomVersionNo(),
                line.sourceBomLineNo(),
                line.sourceBomPath(),
                line.productId(),
                line.productCode(),
                line.productName(),
                line.productSpec(),
                line.productUnit(),
                line.netWeight(),
                line.grossWeight(),
                line.warehouseId(),
                line.supplier().id(),
                line.supplier().code(),
                line.supplier().name(),
                line.qty(),
                line.planDeliveryDate()
            );
        }
        var totalQty = resolvedLines.stream()
            .map(ResolvedGeneratedLine::qty)
            .reduce(BigDecimal.ZERO, BigDecimal::add);
        var summary = new LinkedHashMap<String, Object>();
        summary.put("id", requisitionId);
        summary.put("billNo", billNo);
        summary.put("sourcePlanNo", normalizedPlanNo);
        summary.put("supplierId", commonSupplier.id());
        summary.put("supplierCode", commonSupplier.code());
        summary.put("supplierName", commonSupplier.name());
        summary.put("supplier", commonSupplier.name());
        summary.put("status", BillStatus.DRAFT.name());
        summary.put("lineCount", resolvedLines.size());
        summary.put("totalQty", totalQty);
        return summary;
    }

    public Map<String, Object> detail(String billNo) {
        var normalizedBillNo = validationService.required(billNo, "采购申请单号");
        var headers = jdbcTemplate.queryForList("""
            SELECT requisition.id::text AS id,
                   requisition.bill_no AS "billNo",
                   requisition.source_plan_id::text AS "sourcePlanId",
                   requisition.source_plan_no AS "sourcePlanNo",
                   requisition.supplier_id::text AS "supplierId",
                   COALESCE(requisition.supplier_code_snapshot, supplier.code) AS "supplierCode",
                   COALESCE(requisition.supplier_name_snapshot, supplier.name) AS "supplierName",
                   to_char(requisition.bill_date, 'YYYY-MM-DD') AS "billDate",
                   requisition.department,
                   requisition.status,
                   requisition.total_amount AS "totalAmount",
                   requisition.owner_name AS "ownerName",
                   requisition.version
            FROM purchase_requisition requisition
            LEFT JOIN md_supplier supplier ON supplier.id = requisition.supplier_id
            WHERE requisition.bill_no = ?
            """, normalizedBillNo);
        if (headers.isEmpty()) {
            throw notFound("采购申请不存在");
        }
        var lines = jdbcTemplate.queryForList("""
            SELECT line.id::text AS id,
                   line.line_no AS "lineNo",
                   line.source_plan_id::text AS "sourcePlanId",
                   line.source_plan_line_id::text AS "sourcePlanLineId",
                   plan_line.line_no AS "sourcePlanLineNo",
                   line.source_plan_no AS "sourcePlanNo",
                   line.source_task_id::text AS "sourceTaskId",
                   line.source_level AS "sourceLevel",
                   line.source_bom_line_id::text AS "sourceBomLineId",
                   line.source_bom_code_snapshot AS "sourceBomCode",
                   line.source_bom_version_no AS "sourceBomVersionNo",
                   line.source_bom_line_no AS "sourceBomLineNo",
                   line.source_bom_path AS "sourceBomPath",
                   line.product_id::text AS "productId",
                   COALESCE(line.product_code_snapshot, product.code) AS "productCode",
                   COALESCE(line.product_name_snapshot, product.name) AS "productName",
                   COALESCE(line.product_spec_snapshot, product.spec, '') AS spec,
                   COALESCE(line.product_unit_snapshot, product.unit, '') AS unit,
                   COALESCE(line.net_weight_snapshot, product.net_weight) AS "netWeight",
                   COALESCE(line.gross_weight_snapshot, product.gross_weight) AS "grossWeight",
                   line.warehouse_id::text AS "warehouseId",
                   warehouse.code AS "warehouseCode",
                   line.supplier_id::text AS "supplierId",
                   COALESCE(line.supplier_code_snapshot, supplier.code) AS "supplierCode",
                   COALESCE(line.supplier_name_snapshot, supplier.name) AS "supplierName",
                   line.qty,
                   COALESCE(line.ordered_qty, 0) AS "orderedQty",
                   COALESCE(line.planned_qty, 0) AS "plannedQty",
                   GREATEST(
                       line.qty - COALESCE(line.ordered_qty, 0) - COALESCE(line.planned_qty, 0),
                       0
                   ) AS "remainingQty",
                   to_char(line.plan_delivery_date, 'YYYY-MM-DD') AS "planDeliveryDate"
            FROM purchase_requisition requisition
            JOIN purchase_requisition_line line ON line.requisition_id = requisition.id
            JOIN md_product product ON product.id = line.product_id
            LEFT JOIN production_plan_line plan_line ON plan_line.id = line.source_plan_line_id
            LEFT JOIN md_warehouse warehouse ON warehouse.id = line.warehouse_id
            LEFT JOIN md_supplier supplier ON supplier.id = line.supplier_id
            WHERE requisition.bill_no = ?
            ORDER BY line.line_no
            """, normalizedBillNo);
        return Map.of(
            "action", "DETAIL",
            "document", headers.get(0),
            "lines", lines
        );
    }

    @Transactional
    public Map<String, Object> saveDraft(PurchaseRequisitionDraftRequest request) {
        if (request == null || request.lines() == null || request.lines().isEmpty()) {
            throw badRequest("采购申请至少需要保留一条分录");
        }
        var billNo = validationService.required(request.billNo(), "采购申请单号");
        if (request.version() == null || request.version() < 0) {
            throw badRequest("version 不能为空或小于 0");
        }
        var header = lockRequisition(billNo);
        requireStatus(header, BillStatus.DRAFT, "只有草稿采购申请可以修改");
        if (numberValue(header.get("version")).longValue() != request.version()) {
            throw conflict("采购申请已被其他操作修改，请刷新后重试");
        }

        var currentLines = jdbcTemplate.queryForList("""
            SELECT id::text AS id,
                   line_no AS "lineNo",
                   COALESCE(ordered_qty, 0) AS "orderedQty",
                   COALESCE(planned_qty, 0) AS "plannedQty"
            FROM purchase_requisition_line
            WHERE requisition_id = ?::uuid
            ORDER BY line_no
            FOR UPDATE
            """, header.get("id"));
        var currentById = new LinkedHashMap<String, Map<String, Object>>();
        for (var line : currentLines) {
            currentById.put(String.valueOf(line.get("id")), line);
        }

        var requestedIds = new HashSet<String>();
        var changes = new ArrayList<DraftLineChange>();
        var requestLineNo = 1;
        for (var line : request.lines()) {
            if (line == null) {
                throw badRequest("第 " + requestLineNo + " 行不能为空");
            }
            var id = requiredUuid(line.id(), "第 " + requestLineNo + " 行主键");
            if (!requestedIds.add(id)) {
                throw badRequest("采购申请分录不能重复");
            }
            var current = currentById.get(id);
            if (current == null) {
                throw badRequest("草稿不支持新增或替换采购申请分录");
            }
            var qty = validationService.positive(line.qty(), "第 " + current.get("lineNo") + " 行数量");
            var occupied = decimalValue(current.get("orderedQty")).add(decimalValue(current.get("plannedQty")));
            if (qty.compareTo(occupied) < 0) {
                throw conflict("第 " + current.get("lineNo") + " 行数量不能小于已占用数量 " + occupied.stripTrailingZeros().toPlainString());
            }
            changes.add(new DraftLineChange(
                id,
                qty,
                resolveDraftSupplier(line.supplierCode())
            ));
            requestLineNo += 1;
        }

        for (var current : currentLines) {
            var id = String.valueOf(current.get("id"));
            if (requestedIds.contains(id)) {
                continue;
            }
            var occupied = decimalValue(current.get("orderedQty")).add(decimalValue(current.get("plannedQty")));
            if (occupied.compareTo(BigDecimal.ZERO) > 0) {
                throw conflict("第 " + current.get("lineNo") + " 行已被下游占用，不能删除");
            }
            jdbcTemplate.update("""
                DELETE FROM purchase_requisition_line
                WHERE id = ?::uuid
                  AND requisition_id = ?::uuid
                """, id, header.get("id"));
        }
        for (var change : changes) {
            jdbcTemplate.update("""
                UPDATE purchase_requisition_line
                SET qty = ?,
                    supplier_id = ?::uuid,
                    supplier_code_snapshot = ?,
                    supplier_name_snapshot = ?,
                    updated_at = now()
                WHERE id = ?::uuid
                  AND requisition_id = ?::uuid
                """,
                change.qty(),
                change.supplier().id(),
                change.supplier().code(),
                change.supplier().name(),
                change.id(),
                header.get("id")
            );
        }

        var commonSupplier = commonSupplier(changes.stream().map(DraftLineChange::supplier).toList());
        var updated = jdbcTemplate.update("""
            UPDATE purchase_requisition
            SET supplier_id = ?::uuid,
                supplier_code_snapshot = ?,
                supplier_name_snapshot = ?,
                updated_at = now(),
                version = version + 1
            WHERE id = ?::uuid
              AND status = 'DRAFT'
              AND version = ?
            """,
            commonSupplier.id(),
            commonSupplier.code(),
            commonSupplier.name(),
            header.get("id"),
            request.version()
        );
        if (updated != 1) {
            throw conflict("采购申请已被其他操作修改，本次保存已回滚");
        }
        return detail(billNo);
    }

    @Transactional
    public Map<String, Object> audit(String billNo) {
        var normalizedBillNo = validationService.required(billNo, "采购申请单号");
        var header = lockRequisition(normalizedBillNo);
        requireStatus(header, BillStatus.DRAFT, "只有草稿采购申请可以审核");
        var lines = jdbcTemplate.queryForList("""
            SELECT line_no AS "lineNo", qty
            FROM purchase_requisition_line
            WHERE requisition_id = ?::uuid
            ORDER BY line_no
            FOR UPDATE
            """, header.get("id"));
        if (lines.isEmpty()) {
            throw badRequest("采购申请至少需要一条分录");
        }
        for (var line : lines) {
            validationService.positive((BigDecimal) line.get("qty"), "第 " + line.get("lineNo") + " 行数量");
        }
        transitionLocked(header, BillStatus.DRAFT, BillStatus.AUDITED, "采购申请状态已变化，本次审核已回滚");
        return detail(normalizedBillNo);
    }

    @Transactional
    public Map<String, Object> reverse(String billNo) {
        var normalizedBillNo = validationService.required(billNo, "采购申请单号");
        var header = lockRequisition(normalizedBillNo);
        requireStatus(header, BillStatus.AUDITED, "只有已审核且未下推的采购申请可以反审核");
        var downstream = jdbcTemplate.queryForObject("""
            SELECT
                (SELECT COUNT(*)
                 FROM purchase_plan
                 WHERE source_requisition_id = ?::uuid
                   AND status = 'AUDITED')
                +
                (SELECT COUNT(*) FROM purchase_requisition_line
                 WHERE requisition_id = ?::uuid
                   AND COALESCE(ordered_qty, 0) > 0)
            """, Integer.class, header.get("id"), header.get("id"));
        if (downstream != null && downstream > 0) {
            throw conflict("采购申请已有采购计划或采购订单占用，不能反审核");
        }
        jdbcTemplate.update("""
            DELETE FROM purchase_plan
            WHERE source_requisition_id = ?::uuid
              AND status = 'DRAFT'
            """, header.get("id"));
        jdbcTemplate.update("""
            UPDATE purchase_requisition_line
            SET planned_qty = 0,
                updated_at = now()
            WHERE requisition_id = ?::uuid
              AND COALESCE(planned_qty, 0) <> 0
            """, header.get("id"));
        transitionLocked(header, BillStatus.AUDITED, BillStatus.DRAFT, "采购申请状态已变化，本次反审核已回滚");
        return detail(normalizedBillNo);
    }

    @Transactional
    public Map<String, Object> pushDown(String billNo) {
        var normalizedBillNo = validationService.required(billNo, "采购申请单号");
        var header = lockRequisition(normalizedBillNo);
        requireStatus(header, BillStatus.AUDITED, "只有已审核采购申请可以下推采购计划");

        var existingPlans = jdbcTemplate.queryForObject("""
            SELECT COUNT(*)
            FROM purchase_plan
            WHERE source_requisition_id = ?::uuid
            """, Integer.class, header.get("id"));
        if (existingPlans != null && existingPlans > 0) {
            throw conflict("采购申请已下推采购计划，不能重复下推");
        }

        var rows = jdbcTemplate.queryForList("""
            SELECT line.id::text AS id,
                   line.line_no AS "lineNo",
                   line.product_id::text AS "productId",
                   COALESCE(line.product_code_snapshot, product.code) AS "productCode",
                   COALESCE(line.product_name_snapshot, product.name) AS "productName",
                   COALESCE(line.product_spec_snapshot, product.spec, '') AS spec,
                   COALESCE(line.product_unit_snapshot, product.unit, '') AS unit,
                   COALESCE(line.net_weight_snapshot, product.net_weight) AS "netWeight",
                   COALESCE(line.gross_weight_snapshot, product.gross_weight) AS "grossWeight",
                   line.warehouse_id::text AS "warehouseId",
                   line.supplier_id::text AS "supplierId",
                   supplier.code AS "supplierCode",
                   supplier.name AS "supplierName",
                   supplier.enabled AS "supplierEnabled",
                   supplier.audit_status AS "supplierAuditStatus",
                   line.qty,
                   COALESCE(line.ordered_qty, 0) AS "orderedQty",
                   COALESCE(line.planned_qty, 0) AS "plannedQty",
                   line.plan_delivery_date AS "planDeliveryDateValue"
            FROM purchase_requisition_line line
            JOIN md_product product ON product.id = line.product_id
            LEFT JOIN md_supplier supplier ON supplier.id = line.supplier_id
            WHERE line.requisition_id = ?::uuid
            ORDER BY line.line_no
            FOR UPDATE OF line
            """, header.get("id"));
        if (rows.isEmpty()) {
            throw conflict("采购申请没有可下推分录");
        }

        var positiveLines = new ArrayList<PushDownLine>();
        var missingSuppliers = new ArrayList<String>();
        for (var row : rows) {
            var remaining = decimalValue(row.get("qty"))
                .subtract(decimalValue(row.get("orderedQty")))
                .subtract(decimalValue(row.get("plannedQty")));
            if (remaining.compareTo(BigDecimal.ZERO) <= 0) {
                continue;
            }
            var validSupplier = row.get("supplierId") != null
                && Boolean.TRUE.equals(row.get("supplierEnabled"))
                && "AUDITED".equals(String.valueOf(row.get("supplierAuditStatus")));
            if (!validSupplier) {
                missingSuppliers.add("第 " + row.get("lineNo") + " 行（" + row.get("productCode") + "）");
                continue;
            }
            positiveLines.add(new PushDownLine(row, remaining));
        }
        if (!missingSuppliers.isEmpty()) {
            throw conflict(String.join("、", missingSuppliers) + " 缺少已审核启用的供应商，不能下推");
        }
        if (positiveLines.isEmpty()) {
            throw conflict("采购申请没有剩余可下推数量");
        }

        var grouped = new LinkedHashMap<String, List<PushDownLine>>();
        for (var line : positiveLines) {
            grouped.computeIfAbsent(line.supplierId(), ignored -> new ArrayList<>()).add(line);
        }

        var plans = new ArrayList<Map<String, Object>>();
        try {
            for (var entry : grouped.entrySet()) {
                var supplierLines = entry.getValue();
                var first = supplierLines.get(0);
                var planNo = numberingService.nextBillNo("purchasePlan");
                var plan = jdbcTemplate.queryForMap("""
                    INSERT INTO purchase_plan (
                        bill_no, source_requisition_id, source_requisition_no,
                        supplier_id, supplier_code_snapshot, supplier_name_snapshot,
                        bill_date, department, status, owner_name
                    )
                    VALUES (?, ?::uuid, ?, ?::uuid, ?, ?, ?::date, ?, ?, ?)
                    RETURNING id::text AS id, bill_no AS "billNo", status
                    """,
                    planNo,
                    header.get("id"),
                    normalizedBillNo,
                    first.supplierId(),
                    first.supplierCode(),
                    first.supplierName(),
                    header.get("billDate"),
                    header.get("department"),
                    BillStatus.DRAFT.name(),
                    header.get("ownerName")
                );

                var planId = String.valueOf(plan.get("id"));
                var lineNo = 1;
                var totalQty = BigDecimal.ZERO;
                for (var line : supplierLines) {
                    jdbcTemplate.update("""
                        INSERT INTO purchase_plan_line (
                            plan_id, line_no, source_requisition_line_id,
                            source_requisition_no, source_requisition_line_no,
                            product_id, product_code_snapshot, product_name_snapshot,
                            product_spec_snapshot, product_unit_snapshot,
                            net_weight_snapshot, gross_weight_snapshot, warehouse_id,
                            qty, plan_delivery_date
                        )
                        VALUES (
                            ?::uuid, ?, ?::uuid, ?, ?, ?::uuid, ?, ?, ?, ?, ?, ?,
                            ?::uuid, ?, ?::date
                        )
                        """,
                        planId,
                        lineNo,
                        line.id(),
                        normalizedBillNo,
                        line.sourceLineNo(),
                        line.productId(),
                        line.productCode(),
                        line.productName(),
                        line.spec(),
                        line.unit(),
                        line.netWeight(),
                        line.grossWeight(),
                        line.warehouseId(),
                        line.remainingQty(),
                        line.planDeliveryDate()
                    );
                    totalQty = totalQty.add(line.remainingQty());
                    lineNo += 1;
                }

                var summary = new LinkedHashMap<String, Object>();
                summary.put("id", planId);
                summary.put("billNo", planNo);
                summary.put("sourceRequisitionNo", normalizedBillNo);
                summary.put("supplierId", first.supplierId());
                summary.put("supplierCode", first.supplierCode());
                summary.put("supplierName", first.supplierName());
                summary.put("status", BillStatus.DRAFT.name());
                summary.put("lineCount", supplierLines.size());
                summary.put("totalQty", totalQty);
                plans.add(summary);
            }
        } catch (DataIntegrityViolationException exception) {
            throw conflict("采购申请已被并发下推或来源占用已变化，本次下推已全部回滚");
        }

        var headerUpdated = jdbcTemplate.update("""
            UPDATE purchase_requisition
            SET updated_at = now(),
                version = version + 1
            WHERE id = ?::uuid
              AND status = 'AUDITED'
              AND version = ?
            """, header.get("id"), numberValue(header.get("version")).longValue());
        if (headerUpdated != 1) {
            throw conflict("采购申请已被并发修改，本次下推已全部回滚");
        }
        return Map.of(
            "requisitionNo", normalizedBillNo,
            "purchasePlans", plans
        );
    }

    private ResolvedGeneratedLine resolveGeneratedLine(String planId, int lineNo, GeneratedLine line) {
        if (line == null) {
            throw badRequest("第 " + lineNo + " 行采购需求不能为空");
        }
        var sourcePlanLineId = requiredUuid(line.sourcePlanLineId(), "第 " + lineNo + " 行生产计划分录主键");
        var sourcePlanLineNo = positiveInteger(line.sourcePlanLineNo(), "第 " + lineNo + " 行生产计划分录序号");
        var sourcePlanLine = jdbcTemplate.queryForObject("""
            SELECT COUNT(*)
            FROM production_plan_line
            WHERE id = ?::uuid
              AND plan_id = ?::uuid
              AND line_no = ?
            """, Integer.class, sourcePlanLineId, planId, sourcePlanLineNo);
        if (sourcePlanLine == null || sourcePlanLine != 1) {
            throw badRequest("第 " + lineNo + " 行生产计划分录来源不匹配");
        }

        var sourceTaskId = optionalUuid(line.sourceTaskId(), "第 " + lineNo + " 行生产任务主键");
        if (sourceTaskId != null) {
            var task = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM production_task
                WHERE id = ?::uuid
                  AND plan_id = ?::uuid
                """, Integer.class, sourceTaskId, planId);
            if (task == null || task != 1) {
                throw badRequest("第 " + lineNo + " 行生产任务来源不匹配");
            }
        }

        var sourceBomLineId = requiredUuid(line.sourceBomLineId(), "第 " + lineNo + " 行 BOM 分录主键");
        var sourceBomLine = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM prod_bom_line WHERE id = ?::uuid",
            Integer.class,
            sourceBomLineId
        );
        if (sourceBomLine == null || sourceBomLine != 1) {
            throw badRequest("第 " + lineNo + " 行 BOM 分录不存在");
        }

        var productId = requiredUuid(line.productId(), "第 " + lineNo + " 行物料主键");
        var product = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM md_product WHERE id = ?::uuid",
            Integer.class,
            productId
        );
        if (product == null || product != 1) {
            throw badRequest("第 " + lineNo + " 行物料不存在");
        }

        var warehouseId = optionalUuid(line.warehouseId(), "第 " + lineNo + " 行仓库主键");
        if (warehouseId != null) {
            var warehouse = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM md_warehouse WHERE id = ?::uuid",
                Integer.class,
                warehouseId
            );
            if (warehouse == null || warehouse != 1) {
                throw badRequest("第 " + lineNo + " 行仓库不存在");
            }
        }

        var sourceLevel = line.sourceLevel() == null ? 0 : line.sourceLevel();
        if (sourceLevel < 0) {
            throw badRequest("第 " + lineNo + " 行来源层级不能小于 0");
        }
        return new ResolvedGeneratedLine(
            lineNo,
            sourcePlanLineId,
            sourceTaskId,
            sourceLevel,
            sourceBomLineId,
            validationService.required(line.sourceBomCode(), "第 " + lineNo + " 行来源 BOM 编码"),
            positiveInteger(line.sourceBomVersionNo(), "第 " + lineNo + " 行来源 BOM 版本"),
            positiveInteger(line.sourceBomLineNo(), "第 " + lineNo + " 行来源 BOM 行号"),
            validationService.optionalText(line.sourceBomPath()),
            productId,
            validationService.required(line.productCode(), "第 " + lineNo + " 行物料编码"),
            validationService.required(line.productName(), "第 " + lineNo + " 行物料名称"),
            validationService.optionalText(line.productSpec()),
            validationService.optionalText(line.productUnit()),
            line.netWeight(),
            line.grossWeight(),
            warehouseId,
            resolveGeneratedSupplier(line.supplierId(), line.supplierCode()),
            validationService.positive(line.qty(), "第 " + lineNo + " 行采购数量"),
            line.planDeliveryDate(),
            validationService.optionalText(line.department())
        );
    }

    private SupplierSnapshot resolveGeneratedSupplier(String supplierId, String supplierCode) {
        var normalizedId = validationService.optionalText(supplierId);
        var normalizedCode = validationService.optionalText(supplierCode);
        if (normalizedId == null && normalizedCode == null) {
            return NO_SUPPLIER;
        }
        if (normalizedId != null) {
            try {
                normalizedId = UUID.fromString(normalizedId).toString();
            } catch (IllegalArgumentException exception) {
                return NO_SUPPLIER;
            }
            var rows = jdbcTemplate.queryForList("""
                SELECT id::text AS id, code, name
                FROM md_supplier
                WHERE id = ?::uuid
                  AND enabled = TRUE
                  AND audit_status = 'AUDITED'
                  AND (?::text IS NULL OR code = ?)
                """, normalizedId, normalizedCode, normalizedCode);
            return rows.isEmpty() ? NO_SUPPLIER : supplierSnapshot(rows.get(0));
        }
        var rows = jdbcTemplate.queryForList("""
            SELECT id::text AS id, code, name
            FROM md_supplier
            WHERE code = ?
              AND enabled = TRUE
              AND audit_status = 'AUDITED'
            """, normalizedCode);
        return rows.isEmpty() ? NO_SUPPLIER : supplierSnapshot(rows.get(0));
    }

    private SupplierSnapshot resolveDraftSupplier(String supplierCode) {
        var normalizedCode = validationService.optionalText(supplierCode);
        if (normalizedCode == null) {
            return NO_SUPPLIER;
        }
        var supplierId = lookupService.lookupEnabledId("md_supplier", normalizedCode, "供应商");
        var rows = jdbcTemplate.queryForList("""
            SELECT id::text AS id, code, name
            FROM md_supplier
            WHERE id = ?::uuid
            """, supplierId);
        if (rows.size() != 1) {
            throw badRequest("供应商不存在、未审核或已禁用");
        }
        return supplierSnapshot(rows.get(0));
    }

    private Map<String, Object> lockRequisition(String billNo) {
        var rows = jdbcTemplate.queryForList("""
            SELECT id::text AS id,
                   bill_no AS "billNo",
                   bill_date AS "billDate",
                   department,
                   owner_name AS "ownerName",
                   status,
                   version
            FROM purchase_requisition
            WHERE bill_no = ?
            FOR UPDATE
            """, billNo);
        if (rows.isEmpty()) {
            throw notFound("采购申请不存在");
        }
        return rows.get(0);
    }

    private void transitionLocked(
        Map<String, Object> header,
        BillStatus from,
        BillStatus to,
        String conflictMessage
    ) {
        var updated = jdbcTemplate.update("""
            UPDATE purchase_requisition
            SET status = ?,
                updated_at = now(),
                version = version + 1
            WHERE id = ?::uuid
              AND status = ?
              AND version = ?
            """,
            to.name(),
            header.get("id"),
            from.name(),
            numberValue(header.get("version")).longValue()
        );
        if (updated != 1) {
            throw conflict(conflictMessage);
        }
    }

    private void requireStatus(Map<String, Object> header, BillStatus expected, String message) {
        if (!expected.name().equals(String.valueOf(header.get("status")))) {
            throw conflict(message);
        }
    }

    private SupplierSnapshot commonSupplier(List<SupplierSnapshot> suppliers) {
        if (suppliers == null || suppliers.isEmpty() || suppliers.get(0).id() == null) {
            return NO_SUPPLIER;
        }
        var first = suppliers.get(0);
        for (var supplier : suppliers) {
            if (supplier.id() == null || !first.id().equals(supplier.id())) {
                return NO_SUPPLIER;
            }
        }
        return first;
    }

    private String commonDepartment(List<ResolvedGeneratedLine> lines) {
        if (lines.isEmpty() || lines.get(0).department() == null) {
            return null;
        }
        var first = lines.get(0).department();
        for (var line : lines) {
            if (!first.equals(line.department())) {
                return null;
            }
        }
        return first;
    }

    private SupplierSnapshot supplierSnapshot(Map<String, Object> row) {
        return new SupplierSnapshot(
            String.valueOf(row.get("id")),
            String.valueOf(row.get("code")),
            String.valueOf(row.get("name"))
        );
    }

    private String requiredUuid(String value, String label) {
        var normalized = validationService.required(value, label);
        try {
            return UUID.fromString(normalized).toString();
        } catch (IllegalArgumentException exception) {
            throw badRequest(label + "格式不正确");
        }
    }

    private String optionalUuid(String value, String label) {
        var normalized = validationService.optionalText(value);
        if (normalized == null) {
            return null;
        }
        try {
            return UUID.fromString(normalized).toString();
        } catch (IllegalArgumentException exception) {
            throw badRequest(label + "格式不正确");
        }
    }

    private Integer positiveInteger(Integer value, String label) {
        if (value == null || value <= 0) {
            throw badRequest(label + "必须大于 0");
        }
        return value;
    }

    private BigDecimal decimalValue(Object value) {
        if (value instanceof BigDecimal decimal) {
            return decimal;
        }
        if (value instanceof Number number) {
            return new BigDecimal(number.toString());
        }
        throw new IllegalStateException("数量字段不是数值");
    }

    private Number numberValue(Object value) {
        if (value instanceof Number number) {
            return number;
        }
        throw new IllegalStateException("version 字段不是数值");
    }

    private ResponseStatusException badRequest(String message) {
        return new ResponseStatusException(HttpStatus.BAD_REQUEST, message);
    }

    private ResponseStatusException conflict(String message) {
        return new ResponseStatusException(HttpStatus.CONFLICT, message);
    }

    private ResponseStatusException notFound(String message) {
        return new ResponseStatusException(HttpStatus.NOT_FOUND, message);
    }

    public record GeneratedLine(
        String sourcePlanLineId,
        Integer sourcePlanLineNo,
        String sourceTaskId,
        Integer sourceLevel,
        String sourceBomLineId,
        String sourceBomCode,
        Integer sourceBomVersionNo,
        Integer sourceBomLineNo,
        String sourceBomPath,
        String productId,
        String productCode,
        String productName,
        String productSpec,
        String productUnit,
        BigDecimal netWeight,
        BigDecimal grossWeight,
        String warehouseId,
        String supplierId,
        String supplierCode,
        String supplierName,
        BigDecimal qty,
        LocalDate planDeliveryDate,
        String department
    ) {
    }

    public record PurchaseRequisitionDraftRequest(
        String billNo,
        Long version,
        List<PurchaseRequisitionLineDraftRequest> lines
    ) {
        public PurchaseRequisitionDraftRequest {
            if (lines == null || lines.isEmpty()) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "采购申请至少需要一条分录");
            }
        }
    }

    public record PurchaseRequisitionLineDraftRequest(
        String id,
        BigDecimal qty,
        String supplierCode
    ) {
    }

    private record SupplierSnapshot(String id, String code, String name) {
    }

    private record ResolvedGeneratedLine(
        int lineNo,
        String sourcePlanLineId,
        String sourceTaskId,
        int sourceLevel,
        String sourceBomLineId,
        String sourceBomCode,
        Integer sourceBomVersionNo,
        Integer sourceBomLineNo,
        String sourceBomPath,
        String productId,
        String productCode,
        String productName,
        String productSpec,
        String productUnit,
        BigDecimal netWeight,
        BigDecimal grossWeight,
        String warehouseId,
        SupplierSnapshot supplier,
        BigDecimal qty,
        LocalDate planDeliveryDate,
        String department
    ) {
    }

    private record DraftLineChange(String id, BigDecimal qty, SupplierSnapshot supplier) {
    }

    private record PushDownLine(Map<String, Object> row, BigDecimal remainingQty) {
        String id() {
            return String.valueOf(row.get("id"));
        }

        Integer sourceLineNo() {
            return ((Number) row.get("lineNo")).intValue();
        }

        String productId() {
            return String.valueOf(row.get("productId"));
        }

        String productCode() {
            return String.valueOf(row.get("productCode"));
        }

        String productName() {
            return String.valueOf(row.get("productName"));
        }

        String spec() {
            return row.get("spec") == null ? null : String.valueOf(row.get("spec"));
        }

        String unit() {
            return row.get("unit") == null ? null : String.valueOf(row.get("unit"));
        }

        Object netWeight() {
            return row.get("netWeight");
        }

        Object grossWeight() {
            return row.get("grossWeight");
        }

        String warehouseId() {
            return row.get("warehouseId") == null ? null : String.valueOf(row.get("warehouseId"));
        }

        String supplierId() {
            return String.valueOf(row.get("supplierId"));
        }

        String supplierCode() {
            return String.valueOf(row.get("supplierCode"));
        }

        String supplierName() {
            return String.valueOf(row.get("supplierName"));
        }

        Object planDeliveryDate() {
            return row.get("planDeliveryDateValue");
        }
    }
}
